definitions:
  model.CreatePostData:
    properties:
      content:
        type: string
      tags:
        items:
          $ref: '#/definitions/model.Tag'
        type: array
      title:
        type: string
      user_id:
        type: integer
    type: object
  model.LikeCommentData:
    properties:
      comment_id:
        type: integer
      like_or_dislike:
        type: boolean
      user_id:
        type: integer
    type: object
  model.Tag:
    properties:
      name:
        type: string
    type: object
  v1.Testtype:
    properties:
      name:
        type: string
      tags:
        items:
          $ref: '#/definitions/model.Tag'
        type: array
    type: object
info:
  contact: {}
paths:
  /post/comment/create:
    post:
      description: Create a comment
      parameters:
      - description: user_id
        in: formData
        name: user_id
        required: true
        type: string
      - description: post_id
        in: formData
        name: post_id
        required: true
        type: string
      - description: content
        in: formData
        name: content
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "用户评论成功"}'
          schema:
            type: string
      tags:
      - Post
  /post/comment/like:
    post:
      consumes:
      - application/json
      description: Like a comment
      parameters:
      - description: LikeCommentData
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.LikeCommentData'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success": true, "message": "点赞成功", "commentlike": commentlike}'
          schema:
            type: string
      tags:
      - Post
  /post/create:
    post:
      consumes:
      - application/json
      description: Create a post
      parameters:
      - description: "22"
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.CreatePostData'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success": true, "message": "发布成功"}'
          schema:
            type: string
      tags:
      - Post
  /post/get_all_tags:
    post:
      description: Get all tags
      responses:
        "200":
          description: '{"success": true, "message": "获取标签成功", "tags":tags}'
          schema:
            type: string
      tags:
      - Post
  /post/get_post_comments:
    post:
      description: Get post comments
      parameters:
      - description: post_id
        in: formData
        name: post_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "获取评论成功", "comments":comments}'
          schema:
            type: string
      tags:
      - Post
  /post/get_post_tags:
    post:
      description: Get post tags
      parameters:
      - description: post_id
        in: formData
        name: post_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "获取标签成功", "post_tags":postTags}'
          schema:
            type: string
      tags:
      - Post
  /user/info:
    post:
      description: ShowUserInfo
      parameters:
      - description: user_id
        in: formData
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: '{"status": true, "message": "查询成功", "data": "model.User"}'
          schema:
            type: string
      tags:
      - User
  /user/login:
    post:
      description: Login
      parameters:
      - description: username
        in: formData
        name: username
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: '{"status": true, "message": "登录成功"}'
          schema:
            type: string
      tags:
      - User
  /user/register:
    post:
      description: Register
      parameters:
      - description: username
        in: formData
        name: username
        required: true
        type: string
      - description: password1
        in: formData
        name: password1
        required: true
        type: string
      - description: password2
        in: formData
        name: password2
        required: true
        type: string
      - description: email
        in: formData
        name: email
        required: true
        type: string
      responses:
        "200":
          description: '{"status": true, "message": "注册成功"}'
          schema:
            type: string
      tags:
      - User
  /user/test:
    post:
      consumes:
      - application/json
      description: Test
      parameters:
      - description: 用户名，密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/v1.Testtype'
      produces:
      - application/json
      responses:
        "200":
          description: '{"status": true, "message": "注册成功"}'
          schema:
            type: string
      tags:
      - User
swagger: "2.0"
